version: 1

formatters:
  short:
    format: "%(asctime)s %(levelname)-6s %(message)s"
  detailed:
    format: "%(asctime)s %(levelname)-6s %(name)s %(filename)s:%(lineno)-4d %(message)s"

handlers:
  console:
    class : logging.StreamHandler
    formatter: short
    level   : DEBUG
    stream  : ext://sys.stdout
  detailed-console:
    class : logging.StreamHandler
    formatter: detailed
    level   : DEBUG
    stream  : ext://sys.stdout

loggers:
  namkha:
    level: DEBUG
    handlers: [detailed-console]
    propagate: false
  root:
    level: DEBUG
    handlers: [console]
    propagate: true
